[build]
  base = "frontend"
  publish = "."
  command = ""

[functions]
  node_bundler = "nft"
  external_node_modules = [
    "@babel/preset-typescript",
    "@tailwindcss/oxide",
    "lightningcss"
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
